version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=catalog
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  web:
    image: catalog-image-v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80" # Change 8080 to your desired port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
    depends_on:
      - mongodb
